<?php

namespace Database\Seeders;

use App\Models\VehicleModel;
use Illuminate\Database\Seeder;

class VehicleModelSeeder extends Seeder
{
    public function run(): void
    {
        $records = [
            [
                'kisyu_cd' => 'CB400SF',
                'iro_cd'   => 'R001',
                'kisyu_nm' => 'CB400SF-V',
                'kisyu_nm_r' => 'CB400SF',
                'kihon'    => 'CB400',
                'kisyu_nm_h' => 'ホンダ CB400スーパーフォア',
                'sre_tan'  => 520000.00,
                'uri_tan'  => 649000.00,
                'g1' => 'SS',
                'g2' => '02',
                'g3' => null,
                'g4' => null,
                'g5' => null,
                'order_no' => 'ORD00001',
                'zei_kbn'  => '1',
            ],
            [
                'kisyu_cd' => 'CB400SF',
                'iro_cd'   => 'B001',
                'kisyu_nm' => 'CB400SF-V',
                'kisyu_nm_r' => 'CB400SF',
                'kihon'    => 'CB400',
                'kisyu_nm_h' => 'ホンダ CB400スーパーフォア',
                'sre_tan'  => 520000.00,
                'uri_tan'  => 649000.00,
                'g1' => 'SS',
                'g2' => '02',
                'g3' => null,
                'g4' => null,
                'g5' => null,
                'order_no' => 'ORD00002',
                'zei_kbn'  => '1',
            ],
            [
                'kisyu_cd' => 'ZX10R',
                'iro_cd'   => 'G001',
                'kisyu_nm' => 'Ninja ZX-10R',
                'kisyu_nm_r' => 'ZX10R',
                'kihon'    => 'ZX10',
                'kisyu_nm_h' => 'カワサキ Ninja ZX-10R',
                'sre_tan'  => 1380000.00,
                'uri_tan'  => 1694000.00,
                'g1' => 'SS',
                'g2' => '02',
                'g3' => null,
                'g4' => null,
                'g5' => null,
                'order_no' => 'ORD00003',
                'zei_kbn'  => '1',
            ],
            [
                'kisyu_cd' => 'MT09',
                'iro_cd'   => 'B002',
                'kisyu_nm' => 'MT-09 SP',
                'kisyu_nm_r' => 'MT09',
                'kihon'    => 'MT09',
                'kisyu_nm_h' => 'ヤマハ MT-09 SP',
                'sre_tan'  => 1020000.00,
                'uri_tan'  => 1254000.00,
                'g1' => 'TO',
                'g2' => '02',
                'g3' => null,
                'g4' => null,
                'g5' => null,
                'order_no' => 'ORD00004',
                'zei_kbn'  => '1',
            ],
            [
                'kisyu_cd' => 'PCX160',
                'iro_cd'   => 'W001',
                'kisyu_nm' => 'PCX160',
                'kisyu_nm_r' => 'PCX160',
                'kihon'    => 'PCX',
                'kisyu_nm_h' => 'ホンダ PCX160',
                'sre_tan'  => 275000.00,
                'uri_tan'  => 341000.00,
                'g1' => 'TO',
                'g2' => '02',
                'g3' => null,
                'g4' => null,
                'g5' => null,
                'order_no' => 'ORD00005',
                'zei_kbn'  => '1',
            ],
            [
                'kisyu_cd' => 'MONKEY',
                'iro_cd'   => 'Y001',
                'kisyu_nm' => 'モンキー125',
                'kisyu_nm_r' => 'MONKEY',
                'kihon'    => 'MONKEY',
                'kisyu_nm_h' => 'ホンダ モンキー125',
                'sre_tan'  => 318000.00,
                'uri_tan'  => 396000.00,
                'g1' => 'TO',
                'g2' => '02',
                'g3' => null,
                'g4' => null,
                'g5' => null,
                'order_no' => 'ORD00006',
                'zei_kbn'  => '1',
            ],
            [
                'kisyu_cd' => 'CRF50F',
                'iro_cd'   => 'R002',
                'kisyu_nm' => 'CRF50F',
                'kisyu_nm_r' => 'CRF50F',
                'kihon'    => 'CRF50',
                'kisyu_nm_h' => 'ホンダ CRF50F',
                'sre_tan'  => 140000.00,
                'uri_tan'  => 176000.00,
                'g1' => 'SS',
                'g2' => '01',
                'g3' => null,
                'g4' => null,
                'g5' => null,
                'order_no' => 'ORD00007',
                'zei_kbn'  => '1',
            ],
            [
                'kisyu_cd' => 'GSX-R1000',
                'iro_cd'   => 'B003',
                'kisyu_nm' => 'GSX-R1000R',
                'kisyu_nm_r' => 'GSX-R1000',
                'kihon'    => 'GSXR1000',
                'kisyu_nm_h' => 'スズキ GSX-R1000R',
                'sre_tan'  => 1760000.00,
                'uri_tan'  => 2178000.00,
                'g1' => 'SS',
                'g2' => '02',
                'g3' => null,
                'g4' => null,
                'g5' => null,
                'order_no' => 'ORD00008',
                'zei_kbn'  => '1',
            ],
        ];

        foreach ($records as $data) {
            VehicleModel::create($data);
        }
    }
}
