<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        $records = [
            [
                'kisyu_cd' => 'CB400SF', 'frame_no' => 'NC31100001',
                'kisyu_nm' => 'ホンダ CB400スーパーフォア', 'iro_cd' => 'R001',
                'name1' => 'CB400 SUPER FOUR', 'name2' => null,
                'keishiki' => 'NC31', 'kisyu_no' => 'CB400SF-V',
                'sre_tan' => 520000.00, 'uri_tan' => 649000.00,
                'maker_code' => 'H-NC31-R001', 'unit' => '台',
                'vehicle_no' => '品川 500 あ 1234',
                'first_reg_date' => '2023-04-01', 'second_reg_date' => null,
                'owner_name' => '山田 太郎', 'owner_kana' => 'ヤマダ タロウ',
                'birth_date' => '1985-06-15', 'gender' => 'M',
                'zip_code' => '150-0001',
                'address1' => '東京都渋谷区神宮前1-1-1',
                'address2' => 'サンプルマンション101',
                'tel' => '03-1234-5678', 'mobile' => '090-1234-5678',
                'has_security_reg' => true,  'security_reg_date' => '2023-04-01',
                'has_theft_insurance' => true,  'theft_insurance_date' => '2023-04-01',
                'has_warranty' => true, 'has_application' => true, 'has_dm' => true,
                'shop_name' => '株式会社バイクショップ東京', 'sale_date' => '2023-03-25',
                'remarks' => null, 'note1' => null, 'note2' => null, 'note3' => null,
            ],
            [
                'kisyu_cd' => 'CB400SF', 'frame_no' => 'NC31100002',
                'kisyu_nm' => 'ホンダ CB400スーパーフォア', 'iro_cd' => 'B001',
                'name1' => 'CB400 SUPER FOUR', 'name2' => null,
                'keishiki' => 'NC31', 'kisyu_no' => 'CB400SF-V',
                'sre_tan' => 520000.00, 'uri_tan' => 649000.00,
                'maker_code' => 'H-NC31-B001', 'unit' => '台',
                'vehicle_no' => '練馬 500 い 5678',
                'first_reg_date' => '2023-06-10', 'second_reg_date' => null,
                'owner_name' => '鈴木 花子', 'owner_kana' => 'スズキ ハナコ',
                'birth_date' => '1990-03-22', 'gender' => 'F',
                'zip_code' => '176-0001',
                'address1' => '東京都練馬区豊玉北2-2-2',
                'address2' => null,
                'tel' => '03-2345-6789', 'mobile' => '080-2345-6789',
                'has_security_reg' => true,  'security_reg_date' => '2023-06-10',
                'has_theft_insurance' => false, 'theft_insurance_date' => null,
                'has_warranty' => true, 'has_application' => true, 'has_dm' => false,
                'shop_name' => '株式会社バイクショップ東京', 'sale_date' => '2023-06-05',
                'remarks' => null, 'note1' => null, 'note2' => null, 'note3' => null,
            ],
            [
                'kisyu_cd' => 'ZX10R', 'frame_no' => 'ZXT00E0001',
                'kisyu_nm' => 'カワサキ Ninja ZX-10R', 'iro_cd' => 'G001',
                'name1' => 'Ninja ZX-10R', 'name2' => 'KRT EDITION',
                'keishiki' => 'ZXT00E', 'kisyu_no' => 'ZX10R-2023',
                'sre_tan' => 1380000.00, 'uri_tan' => 1694000.00,
                'maker_code' => 'K-ZXT00E-G001', 'unit' => '台',
                'vehicle_no' => '世田谷 500 う 9012',
                'first_reg_date' => '2023-09-15', 'second_reg_date' => null,
                'owner_name' => '田中 健一', 'owner_kana' => 'タナカ ケンイチ',
                'birth_date' => '1978-11-30', 'gender' => 'M',
                'zip_code' => '154-0001',
                'address1' => '東京都世田谷区池尻3-3-3',
                'address2' => null,
                'tel' => '03-3456-7890', 'mobile' => '090-3456-7890',
                'has_security_reg' => true,  'security_reg_date' => '2023-09-15',
                'has_theft_insurance' => true,  'theft_insurance_date' => '2023-09-15',
                'has_warranty' => true, 'has_application' => true, 'has_dm' => true,
                'shop_name' => 'カワサキプラザ渋谷', 'sale_date' => '2023-09-10',
                'remarks' => '特別カラー限定モデル',
                'note1' => 'ETC取付済', 'note2' => 'ドライブレコーダー取付済', 'note3' => null,
            ],
            [
                'kisyu_cd' => 'MT09', 'frame_no' => 'B3L0000001',
                'kisyu_nm' => 'ヤマハ MT-09 SP', 'iro_cd' => 'B002',
                'name1' => 'MT-09 SP', 'name2' => null,
                'keishiki' => 'RN69J', 'kisyu_no' => 'MT09SP-2023',
                'sre_tan' => 1020000.00, 'uri_tan' => 1254000.00,
                'maker_code' => 'Y-B3L-B002', 'unit' => '台',
                'vehicle_no' => '足立 400 え 3456',
                'first_reg_date' => '2023-07-20', 'second_reg_date' => null,
                'owner_name' => '佐藤 次郎', 'owner_kana' => 'サトウ ジロウ',
                'birth_date' => '1982-08-05', 'gender' => 'M',
                'zip_code' => '120-0001',
                'address1' => '東京都足立区千住4-4-4',
                'address2' => 'ハイツサトウ202',
                'tel' => '03-4567-8901', 'mobile' => '070-4567-8901',
                'has_security_reg' => true,  'security_reg_date' => '2023-07-20',
                'has_theft_insurance' => true,  'theft_insurance_date' => '2023-07-20',
                'has_warranty' => true, 'has_application' => false, 'has_dm' => true,
                'shop_name' => 'ヤマハバイクショップ北千住', 'sale_date' => '2023-07-15',
                'remarks' => null, 'note1' => 'グリップヒーター装備', 'note2' => null, 'note3' => null,
            ],
            [
                'kisyu_cd' => 'PCX160', 'frame_no' => 'JK05E1000001',
                'kisyu_nm' => 'ホンダ PCX160', 'iro_cd' => 'W001',
                'name1' => 'PCX160', 'name2' => null,
                'keishiki' => 'JK05', 'kisyu_no' => 'PCX160-2023',
                'sre_tan' => 275000.00, 'uri_tan' => 341000.00,
                'maker_code' => 'H-JK05-W001', 'unit' => '台',
                'vehicle_no' => '横浜 125 お 7890',
                'first_reg_date' => '2024-01-15', 'second_reg_date' => null,
                'owner_name' => '高橋 美咲', 'owner_kana' => 'タカハシ ミサキ',
                'birth_date' => '1995-02-14', 'gender' => 'F',
                'zip_code' => '220-0001',
                'address1' => '神奈川県横浜市西区みなとみらい5-5-5',
                'address2' => null,
                'tel' => '045-567-8901', 'mobile' => '080-5678-9012',
                'has_security_reg' => true,  'security_reg_date' => '2024-01-15',
                'has_theft_insurance' => false, 'theft_insurance_date' => null,
                'has_warranty' => true, 'has_application' => true, 'has_dm' => true,
                'shop_name' => 'ホンダドリーム横浜', 'sale_date' => '2024-01-10',
                'remarks' => null, 'note1' => null, 'note2' => null, 'note3' => null,
            ],
            [
                'kisyu_cd' => 'MONKEY', 'frame_no' => 'JB02E5000001',
                'kisyu_nm' => 'ホンダ モンキー125', 'iro_cd' => 'Y001',
                'name1' => 'モンキー125', 'name2' => null,
                'keishiki' => 'JB02', 'kisyu_no' => 'MONKEY125-2023',
                'sre_tan' => 318000.00, 'uri_tan' => 396000.00,
                'maker_code' => 'H-JB02-Y001', 'unit' => '台',
                'vehicle_no' => '大阪 125 か 2345',
                'first_reg_date' => '2023-10-01', 'second_reg_date' => null,
                'owner_name' => '伊藤 幸子', 'owner_kana' => 'イトウ サチコ',
                'birth_date' => '1988-12-20', 'gender' => 'F',
                'zip_code' => '530-0001',
                'address1' => '大阪府大阪市北区梅田6-6-6',
                'address2' => 'グランドビル303',
                'tel' => '06-6789-0123', 'mobile' => '090-6789-0123',
                'has_security_reg' => true,  'security_reg_date' => '2023-10-01',
                'has_theft_insurance' => false, 'theft_insurance_date' => null,
                'has_warranty' => true, 'has_application' => true, 'has_dm' => false,
                'shop_name' => 'ホンダドリーム大阪梅田', 'sale_date' => '2023-09-28',
                'remarks' => null, 'note1' => null, 'note2' => null, 'note3' => null,
            ],
            [
                'kisyu_cd' => 'GSX-R1000', 'frame_no' => 'GT79A100001',
                'kisyu_nm' => 'スズキ GSX-R1000R', 'iro_cd' => 'B003',
                'name1' => 'GSX-R1000R', 'name2' => 'MotoGP REPLICA',
                'keishiki' => 'GT79A', 'kisyu_no' => 'GSXR1000R-2023',
                'sre_tan' => 1760000.00, 'uri_tan' => 2178000.00,
                'maker_code' => 'S-GT79A-B003', 'unit' => '台',
                'vehicle_no' => '名古屋 500 き 6789',
                'first_reg_date' => '2024-02-01', 'second_reg_date' => null,
                'owner_name' => '渡辺 雄大', 'owner_kana' => 'ワタナベ ユウダイ',
                'birth_date' => '1975-04-08', 'gender' => 'M',
                'zip_code' => '460-0001',
                'address1' => '愛知県名古屋市中区栄7-7-7',
                'address2' => null,
                'tel' => '052-890-1234', 'mobile' => '090-7890-1234',
                'has_security_reg' => true,  'security_reg_date' => '2024-02-01',
                'has_theft_insurance' => true,  'theft_insurance_date' => '2024-02-01',
                'has_warranty' => true, 'has_application' => true, 'has_dm' => true,
                'shop_name' => 'スズキバイクショップ名古屋栄', 'sale_date' => '2024-01-28',
                'remarks' => 'レース仕様オプション取付',
                'note1' => 'クイックシフター装備', 'note2' => 'アクションカメラ取付', 'note3' => 'サーキット走行確認済',
            ],
            [
                'kisyu_cd' => 'CRF50F', 'frame_no' => 'AE01E0100001',
                'kisyu_nm' => 'ホンダ CRF50F', 'iro_cd' => 'R002',
                'name1' => 'CRF50F', 'name2' => null,
                'keishiki' => 'AE01', 'kisyu_no' => 'CRF50F-2023',
                'sre_tan' => 140000.00, 'uri_tan' => 176000.00,
                'maker_code' => 'H-AE01-R002', 'unit' => '台',
                'vehicle_no' => null,
                'first_reg_date' => null, 'second_reg_date' => null,
                'owner_name' => '小林 誠', 'owner_kana' => 'コバヤシ マコト',
                'birth_date' => '1970-07-11', 'gender' => 'M',
                'zip_code' => '060-0001',
                'address1' => '北海道札幌市中央区北一条西8-8-8',
                'address2' => null,
                'tel' => '011-901-2345', 'mobile' => '080-8901-2345',
                'has_security_reg' => false, 'security_reg_date' => null,
                'has_theft_insurance' => false, 'theft_insurance_date' => null,
                'has_warranty' => true, 'has_application' => false, 'has_dm' => false,
                'shop_name' => 'ホンダドリーム札幌', 'sale_date' => '2023-05-20',
                'remarks' => 'お子様向け練習用', 'note1' => null, 'note2' => null, 'note3' => null,
            ],
        ];

        foreach ($records as $data) {
            Vehicle::create($data);
        }
    }
}
