<?php

namespace Database\Seeders;

use App\Models\VehicleModel;
use Illuminate\Database\Seeder;

class VehicleModelSeeder extends Seeder
{
    public function run(): void
    {
        $records = [
            [
                'model_code' => 'CB400SF',
                'color_code' => 'R001',
                'model_name' => 'CB400SF-V',
                'model_abbr' => 'CB400SF',
                'base_model' => 'CB400',
                'model_name_kanji' => 'ホンダ CB400スーパーフォア',
                'purchase_price' => 520000.00,
                'selling_price' => 649000.00,
                'g1' => 'SS',
                'g2' => '02',
                'g3' => null,
                'g4' => null,
                'g5' => null,
                'order_number' => 'ORD00001',
                'tax_type' => '1',
            ],
            [
                'model_code' => 'CB400SF',
                'color_code' => 'B001',
                'model_name' => 'CB400SF-V',
                'model_abbr' => 'CB400SF',
                'base_model' => 'CB400',
                'model_name_kanji' => 'ホンダ CB400スーパーフォア',
                'purchase_price' => 520000.00,
                'selling_price' => 649000.00,
                'g1' => 'SS',
                'g2' => '02',
                'g3' => null,
                'g4' => null,
                'g5' => null,
                'order_number' => 'ORD00002',
                'tax_type' => '1',
            ],
            [
                'model_code' => 'ZX10R',
                'color_code' => 'G001',
                'model_name' => 'Ninja ZX-10R',
                'model_abbr' => 'ZX10R',
                'base_model' => 'ZX10',
                'model_name_kanji' => 'カワサキ Ninja ZX-10R',
                'purchase_price' => 1380000.00,
                'selling_price' => 1694000.00,
                'g1' => 'SS',
                'g2' => '02',
                'g3' => null,
                'g4' => null,
                'g5' => null,
                'order_number' => 'ORD00003',
                'tax_type' => '1',
            ],
            [
                'model_code' => 'MT09',
                'color_code' => 'B002',
                'model_name' => 'MT-09 SP',
                'model_abbr' => 'MT09',
                'base_model' => 'MT09',
                'model_name_kanji' => 'ヤマハ MT-09 SP',
                'purchase_price' => 1020000.00,
                'selling_price' => 1254000.00,
                'g1' => 'TO',
                'g2' => '02',
                'g3' => null,
                'g4' => null,
                'g5' => null,
                'order_number' => 'ORD00004',
                'tax_type' => '1',
            ],
            [
                'model_code' => 'PCX160',
                'color_code' => 'W001',
                'model_name' => 'PCX160',
                'model_abbr' => 'PCX160',
                'base_model' => 'PCX',
                'model_name_kanji' => 'ホンダ PCX160',
                'purchase_price' => 275000.00,
                'selling_price' => 341000.00,
                'g1' => 'TO',
                'g2' => '02',
                'g3' => null,
                'g4' => null,
                'g5' => null,
                'order_number' => 'ORD00005',
                'tax_type' => '1',
            ],
            [
                'model_code' => 'MONKEY',
                'color_code' => 'Y001',
                'model_name' => 'モンキー125',
                'model_abbr' => 'MONKEY',
                'base_model' => 'MONKEY',
                'model_name_kanji' => 'ホンダ モンキー125',
                'purchase_price' => 318000.00,
                'selling_price' => 396000.00,
                'g1' => 'TO',
                'g2' => '02',
                'g3' => null,
                'g4' => null,
                'g5' => null,
                'order_number' => 'ORD00006',
                'tax_type' => '1',
            ],
            [
                'model_code' => 'CRF50F',
                'color_code' => 'R002',
                'model_name' => 'CRF50F',
                'model_abbr' => 'CRF50F',
                'base_model' => 'CRF50',
                'model_name_kanji' => 'ホンダ CRF50F',
                'purchase_price' => 140000.00,
                'selling_price' => 176000.00,
                'g1' => 'SS',
                'g2' => '01',
                'g3' => null,
                'g4' => null,
                'g5' => null,
                'order_number' => 'ORD00007',
                'tax_type' => '1',
            ],
            [
                'model_code' => 'GSX-R1000',
                'color_code' => 'B003',
                'model_name' => 'GSX-R1000R',
                'model_abbr' => 'GSX-R1000',
                'base_model' => 'GSXR1000',
                'model_name_kanji' => 'スズキ GSX-R1000R',
                'purchase_price' => 1760000.00,
                'selling_price' => 2178000.00,
                'g1' => 'SS',
                'g2' => '02',
                'g3' => null,
                'g4' => null,
                'g5' => null,
                'order_number' => 'ORD00008',
                'tax_type' => '1',
            ],
        ];

        foreach ($records as $data) {
            VehicleModel::create($data);
        }
    }
}
